POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "email": "user1@gmail.com",
    "password": "123123",
    "username": "Tee Ray",
    "name": "Terry",
    "crews": [],
    "points": [],
    "roles": ["6265b2db149d36fdf68abc32"]
}