PUT http://localhost:5000/crews/62657e696415e50ce69c1ad2
Content-Type: application/json

{
    "name": "Siono Crew",
    "description": "siono",
    "admins": ["62657e436415e50ce69c1acd"],
    "users": ["62657e436415e50ce69c1acd"]
}