POST http://localhost:5000/point
Content-Type: application/json

{
      "latitude":-33.52763520000001,
      "longitude":-70.5888611,
      "title":"TESTING",
      "description":"sdfsf",
      "isPublic":false,
      "state":"6265d24cec436a8590a8a76a",
      "createdBy": ["6265b7c1d2f86446bcd9dc18"],
      "usersShared":["6265b7c1d2f86446bcd9dc18", "6265b78fd2f86446bcd9dc16"]
}