# GET http://localhost:5000/users

# GET http://localhost:5000/crews

# GET http://localhost:5000/roles

# GET http://localhost:5000/pointStates

# GET http://localhost:5000/points

# GET http://localhost:5000/permissions

GET http://localhost:5000/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjViNDEzMTAyYzM4YTI2MjZkMmRjOSIsInVzZXJuYW1lIjoiQVNXIiwiaWF0IjoxNjUwODU0MDI5LCJleHAiOjE2NTA4NjAwNzd9.uEqzXqh6AgxWU-m8bax4hoysAxEebtCJD0rrdprNgtE


# POST http://localhost:5000/login
# Content-Type: application/json

# {
#     "user": "ASW",
#     "password": "123123"
# }

# POST http://localhost:5000/role
# Content-Type: application/json

# {
#     "name": "Admin",
#     "permissions": ["6265af3cf8e74631eaa98c74"]
# }

# {
#     "name": "Curent User",
#     "permissions": ["6265af3cf8e74631eaa98c74"]
# }

# {
#     "name": "Crew Admin",
#     "permissions": ["6265af3cf8e74631eaa98c74"]
# }

# PUT http://localhost:5000/roles/6265b2db149d36fdf68abc32
# Content-Type: application/json

# {
#    "permissions": []
# }